/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// What we configure when we call Amplify.configure. This is the object we pass it. 
// When we call amplify from Terminal, this is how it sets up in directory
const awsmobile = {
    "aws_project_region": "us-east-2"
};


export default awsmobile;
